<?php

namespace App\Providers;

use App\Listeners\RedisListener;
use App\Listeners\SqlListener;
use Illuminate\Database\Events\QueryExecuted;
use Illuminate\Redis\Events\CommandExecuted;
use Illuminate\Support\Facades\Redis;
use Laravel\Lumen\Providers\EventServiceProvider as ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        QueryExecuted::class => [
            SqlListener::class
        ],
        CommandExecuted::class => [
            RedisListener::class
        ]
    ];

    /**
     * Determine if events and listeners should be automatically discovered.
     *
     * @return bool
     */
    public function shouldDiscoverEvents()
    {
        return false;
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        if (config('support.redis_log.enable')) {
            Redis::enableEvents();
        }
    }
}
